In [26]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\godfrey\appdata\local\programs\python\python311\lib\site-packages (3.3.5)
Requirement already satisfied: wheel in c:\users\godfrey\appdata\local\programs\python\python311\lib\site-packages (from lightgbm) (0.40.0)
Requirement already satisfied: numpy in c:\users\godfrey\appdata\local\programs\python\python311\lib\site-packages (from lightgbm) (1.24.2)
Requirement already satisfied: scipy in c:\users\godfrey\appdata\local\programs\python\python311\lib\site-packages (from lightgbm) (1.10.1)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\godfrey\appdata\local\programs\python\python311\lib\site-packages (from lightgbm) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\godfrey\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\godfrey\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (3.1.0)

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import confusion_matrix

In [57]:
data = pd.read_csv(r"C:\Users\GODFREY\Downloads\Data\Data_for_UCI_named.csv")

In [16]:
data.head(5)

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [17]:
data.describe()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5.250000,5.250001,5.250004,5.249997,3.750000,-1.250000,-1.250000,-1.250000,0.525000,0.525000,0.525000,0.525000,0.015731
std,2.742548,2.742549,2.742549,2.742556,0.752160,0.433035,0.433035,0.433035,0.274256,0.274255,0.274255,0.274255,0.036919
min,0.500793,0.500141,0.500788,0.500473,1.582590,-1.999891,-1.999945,-1.999926,0.050009,0.050053,0.050054,0.050028,-0.080760
25%,2.874892,2.875140,2.875522,2.874950,3.218300,-1.624901,-1.625025,-1.624960,0.287521,0.287552,0.287514,0.287494,-0.015557
50%,5.250004,5.249981,5.249979,5.249734,3.751025,-1.249966,-1.249974,-1.250007,0.525009,0.525003,0.525015,0.525002,0.017142
75%,7.624690,7.624893,7.624948,7.624838,4.282420,-0.874977,-0.875043,-0.875065,0.762435,0.762490,0.762440,0.762433,0.044878
max,9.999469,9.999837,9.999450,9.999443,5.864418,-0.500108,-0.500072,-0.500025,0.999937,0.999944,0.999982,0.999930,0.109403

In [7]:
data.shape

(10000, 14)

In [8]:
data.drop('stab', axis=1, inplace=True)

In [9]:
data.shape

(10000, 13)

In [10]:
data.head(5)

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,unstable

In [58]:
label_encoder = LabelEncoder()
data['stabf_encoded'] = label_encoder.fit_transform(data['stabf'])

In [59]:
# Split the data into features (x) and target variable (y)
x = data.drop(['stab', 'stabf', 'stabf_encoded'], axis=1)
y = data['stabf_encoded']

# Split the data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [60]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [61]:
#Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=1)
rf_classifier.fit(x_train_scaled, y_train)
rf_predictions = rf_classifier.predict(x_test_scaled)
rf_accuracy = accuracy_score(y_test, rf_predictions)

# Extra Trees Classifier
et_classifier = ExtraTreesClassifier(random_state=1)
et_classifier.fit(x_train_scaled, y_train)
et_predictions = et_classifier.predict(x_test_scaled)
et_accuracy = accuracy_score(y_test, et_predictions)

# XGBoost Classifier
xgb_classifier = XGBClassifier(random_state=1)
xgb_classifier.fit(x_train_scaled, y_train)
xgb_predictions = xgb_classifier.predict(x_test_scaled)
xgb_accuracy = accuracy_score(y_test, xgb_predictions)

# LightGBM Classifier
lgbm_classifier = LGBMClassifier(random_state=1)
lgbm_classifier.fit(x_train_scaled, y_train)
lgbm_predictions = lgbm_classifier.predict(x_test_scaled)
lgbm_accuracy = accuracy_score(y_test, lgbm_predictions)

print("Random Forest Accuracy:", round(rf_accuracy, 4))
print("Extra Trees Accuracy:", round(et_accuracy, 4))
print("XGBoost Accuracy:", round(xgb_accuracy, 4))
print("LightGBM Accuracy:", round(lgbm_accuracy, 4))

Random Forest Accuracy: 0.929
Extra Trees Accuracy: 0.928
XGBoost Accuracy: 0.9455
LightGBM Accuracy: 0.9395

In [65]:
et_classifier = ExtraTreesClassifier(random_state=1)
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 4, 6],
    'min_samples_leaf': [1, 2, 3]
}

random_search = RandomizedSearchCV(et_classifier, param_distributions=param_grid, cv=5, n_iter=10, scoring='accuracy', n_jobs=-1, verbose=1, random_state=1)
random_search.fit(x_train_scaled, y_train)

best_params = random_search.best_params_

print("Best Hyperparameters:")
print(best_params)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best Hyperparameters:
{'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_depth': 10}

In [67]:
et_classifier_initial = ExtraTreesClassifier(random_state=1)
et_classifier_initial.fit(x_train_scaled, y_train)
y_pred_initial = et_classifier_initial.predict(x_test_scaled)
accuracy_initial = accuracy_score(y_test, y_pred_initial)

et_classifier_optimal = ExtraTreesClassifier(n_estimators=100, max_depth=10, min_samples_split=2, min_samples_leaf=1, random_state=1)
et_classifier_optimal.fit(x_train_scaled, y_train)
y_pred_optimal = et_classifier_optimal.predict(x_test_scaled)
accuracy_optimal = accuracy_score(y_test, y_pred_optimal)

if accuracy_optimal > accuracy_initial:
    print("The accuracy of the new optimal model is higher than the initial model.")
elif accuracy_optimal < accuracy_initial:
    print("The accuracy of the new optimal model is lower than the initial model.")
else:
    print("The accuracy of the new optimal model is the same as the initial model.")

The accuracy of the new optimal model is lower than the initial model.

In [68]:
et_classifier_optimal = ExtraTreesClassifier(n_estimators=100, max_depth=10, min_samples_split=2, min_samples_leaf=1, random_state=1)
et_classifier_optimal.fit(x_train_scaled, y_train)

feature_importances = et_classifier_optimal.feature_importances_
feature_importances_df = pd.DataFrame({'Feature': x.columns, 'Importance': feature_importances})
feature_importances_df.sort_values(by='Importance', ascending=False, inplace=True)

most_important_feature = feature_importances_df.iloc[0]['Feature']
least_important_feature = feature_importances_df.iloc[-1]['Feature']

print("Most Important Feature:", most_important_feature)
print("Least Important Feature:", least_important_feature)

Most Important Feature: tau2
Least Important Feature: p4

In [28]:
TP = 256
FP = 1380
FN = 45
TN = 20

accuracy = (TP + TN) / (TP + FP + FN + TN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1_score = 2 * (precision * recall) / (precision + recall)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)

Accuracy: 0.16225749559082892
Precision: 0.15647921760391198
Recall: 0.8504983388704319
F1 Score: 0.26432627774909656